apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: noprod-root-app
  namespace: openshift-gitops
spec:
  project: default
  source:
    repoURL: https://github.com/lfalero14/gitops-middleware-app.git
    targetRevision: HEAD
    path: ./app-of-apps/child-apps/noprod
    directory:
      recurse: false
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
